---
name: David Muneza                      # Real name of the person
  org: UR                               # Organisation/team they work in
  username: davidmuneza                     # username on the lab machine
  github: davidmuneza                       # github user account
  git:                                     # git configuration on the lab machines
    user:
      name: David Muneza
      email: dmunezak@ur.ac.rw
    core:
      editor:
        name: vim
        package:
          RedHat: vim
          Debian: vim
