---
name: Walu Gondwe                          # Real name of the person
    org: MUST/Malawi                       # Organisation/team they work in
    username: walusungu.gondwe             # username on the lab machine
    github: agondway                       # github user account
    git:                                     # git configuration on the lab machines
      user:
        name: Walu Gondwe
        email: wgondwe@bintelanalytics.mw
      core:
        editor:
          name: vim
          package:
            RedHat: vim
            Debian: vim
