---
site_name: entebbe
ansible_user: ubuntu
prerequisites:
  Debian:
    - vim
    - make
    - git
    - python-pip
    - python-setuptools
    - python-dev
    - libssl-dev
    - gcc
  RedHat:
    - vim
    - make
    - git
    - python-pip
    - python-setuptools
    - python-devel
    - gcc
