---
site_name: meraka
ansible_user: ubuntu
prerequisites:
  Debian:
    - vim
    - make
    - git
    - python-pip
    - python-setuptools
    - python-dev
    - libssl-dev
    - gcc
    - nano
    - joe
  RedHat:
    - vim
    - make
    - git
    - python-pip
    - python-setuptools
    - python-devel
    - gcc

# Add participants in this list - it is used to set  up the machines for them.
  # - name: Bruce  Becker
  #   org: CSIR
  #   username: brucellino
  #   git:
  #     name: Bruce Becker
  #     email: brucellino@gmail.com
  #     editor: vim
  #     github: brucellino

participants:
  - name: Bruce  Becker                      # Real name of the person
    org: CSIR                                # Organisation/team they work in
    username: brucellino                     # username on the lab machine
    github: brucellino                       # github user account
    git:                                     # git configuration on the lab machines
      user:
        name: Bruce Becker
        email: brucellino@gmail.com
      core:
        editor:
          name: vim
          package:
            RedHat: vim
            Debian: vim

  - name: Siju Mammen                      # Real name of the person
    org: CSIR                                # Organisation/team they work in
    username: samshive                     # username on the lab machine
    github: samshive                       # github user account
    git:                                     # git configuration on the lab machines
      user:
        name: samshive
        email: samshive@gmail.com
      core:
        editor:
          name: nano
          package:
            RedHat: nano
            Debian: nano

  - name: John Hay                      # Real name of the person
    org: CSIR                                # Organisation/team they work in
    username: jhay                     # username on the lab machine
    github: JohnHay                       # github user account
    git:                                     # git configuration on the lab machines
      user:
        name: John Hay
        email: john@sanren.ac.za
      core:
        editor:
          name: vim
          package:
            RedHat: vim
            Debian: vim

  - name: Claude Fortune                      # Real name of the person
    org: CSIR                                # Organisation/team they work in
    username: cfortune                     # username on the lab machine
    github: cfortune-csir                       # github user account
    git:                                     # git configuration on the lab machines
      user:
        name: Claude Fortune
        email: cfortune@csir.co.za
  - name: funny guy                      # Real name of the person
    org: loony bin                                # Organisation/team they work in
    username: funny                     # username on the lab machine
    github: funnyguy                       # github user account
    git:                                     # git configuration on the lab machines
      user:
        name: Bruce Becker
        email: brucellino@gmail.com
      core:
        editor:
          name: vim
          package:
            RedHat: vim
            Debian: vim
