---
site_name: meraka
ansible_user: ubuntu
prerequisites:
  Debian:
    - vim
    - make
    - git
    - python-pip
    - python-setuptools
    - python-dev
    - libssl-dev
    - gcc
    - nano
    - joe
  RedHat:
    - vim
    - make
    - git
    - python-pip
    - python-setuptools
    - python-devel
    - gcc

# Add participants in this list - it is used to set  up the machines for them.
  # - name: Bruce  Becker
  #   org: CSIR
  #   username: brucellino
  #   git:
  #     name: Bruce Becker
  #     email: brucellino@gmail.com
  #     editor: vim
  #     github: brucellino

participants:
  - name: Bruce  Becker                      # Real name of the person
    org: CSIR                                # Organisation/team they work in
    username: brucellino                     # username on the lab machine
    github: brucellino                       # github user account
    git:                                     # git configuration on the lab machines
      user:
        name: Bruce Becker
        email: brucellino@gmail.com
      core:
        editor:
          name: vim
          package:
            RedHat: vim
            Debian: vim
            
            
    - name: Kasadra Pillay                      # Real name of the person
    org: CSIR                                # Organisation/team they work in
    username: linux                     # username on the lab machine
    github: Kasandra-SANReN                       # github user account
    git:                                     # git configuration on the lab machines
      user:
        name: Kasandra
        email: kasandra@sanren.ac.za
      core:
        editor:
          name: vim
          package:
            RedHat: vim
            Debian: vim
