---
- name: Mohamed A. Ali                      # Real name of the person
  org: somlaiREN                                # Organisation/team they work in
  	username: mjarfadhi                     # username on the lab machine
  	github: mjarfadhi                       # github user account
  	git:                                     # git configuration on the lab machines
  	user:
  	     name: Mohamed A. Ali
  	     email: ict@psu.edu.so
 	     core:
 	       editor:
 	         name: vim
 	         package:
 	           RedHat: vim
 	           Debian: vim
